shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("products.urls")),
    path("",include("user.urls")),
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser,BaseUserManager,PermissionsMixin
from django.utils.translation import gettext_lazy as _

# Create your models here.

class CustomUserManager (BaseUserManager):

    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('Users must have an email address'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self,email,password,**extra_fields):
        user = self.create_user(email,password,**extra_fields)
        user.is_active = True
        user.is_superuser = True
        user.is_staff = True
        user.save()
        return user

class CustomUser (AbstractBaseUser, PermissionsMixin):

    is_staff = models.BooleanField(_("Is staff"),default=False)
    email = models.EmailField(verbose_name=_("Email"),unique = True)
    secondEmail = models.EmailField(verbose_name=_("Secondary email"),null=True,blank=True,unique=True)
    first_name = models.CharField(verbose_name=_("Fisrt name"),null= False,blank=False,max_length=50)
    last_name = models.CharField(verbose_name=_("Last name"),null= False,blank=False,max_length=50)
    birth_date = models.DateField(verbose_name=_("Birth date"))
    tel = models.CharField(verbose_name=_("Phone number"),max_length=9,null = True,unique=True)
    country = models.CharField(verbose_name=_("Country"),max_length=20, null=True)
    region = models.CharField(verbose_name=_("Region"),max_length=20,null=True)
    zipCode = models.IntegerField(verbose_name=_("Zip code"),null=True)
    username = models.CharField(verbose_name=_("User name"),max_length=10,null = True)
    address = models.CharField(verbose_name = _("Address"), max_length= 255,null = True)
    profileImage = models.ImageField(null=True,blank=True,upload_to="user/profileImages")
    date_joined = models.DateTimeField(auto_now_add= True)


    objects = CustomUserManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name","last_name","birth_date"]

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"
        get_latest_by = "date_joined"

    
    def __str__(self) -> str:
        return self.last_name + " " + self.first_name

templates/a.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Title{% endblock title %}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
        
        {% block style %}
            
        {% endblock style %}
            
    </head>
    <body>
        <header>
            <div id="headertop">
                <p>Bienvenue dans la boutique de commerce électronique en ligne DIC1 shop.</p>
                <div>
                    <address>
                        Suivez-nous: 
                        <div>
                            <a href="#"><img src="{% static 'img/twitter.svg' %}" alt="logo twitter"></a>
                            <a href="#"><img src="{% static 'img/faceb.svg' %}" alt="logo facebook"></a>
                            <a href="#"><img src="{% static 'img/pinterest.svg' %}" alt="logo pinterest"></a>
                            <a href="#"><img src="{% static 'img/reddit.svg' %}" alt="logo reddit"></i></a>
                            <a href="#"><img src="{% static 'img/ytb.svg' %}" alt="logo youtube"></a>
                            <a href="#"><img src="{% static 'img/insta.svg' %}" alt="logo instagram"></a>
                        </div>
                    </address>
                    <div>
                        <div class="select-container">
                            <span class= "selected">Fra</span>
                            <div class = "select-dropdown hidden">
                                <span class = "option fr">Fra</span>
                                <span class="option en">Eng</span>
                            </div>
                            <div class = "select-icon">
                                <img src="{% static 'img/chevron-down.svg' %}" alt="logo chevron down">
                            </div>
                        </div>
                        <div class="select-container">
                            <span class= "selected">En USD</span>
                            <div class = "select-dropdown hidden">
                                <span class = "option usd">En USD</span>
                                <span class = "option eur">En EUR</span>
                            </div>
                            <div class = "select-icon">
                                <img src="{% static 'img/chevron-down.svg' %}" alt="logo chevron down">
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
            <div id="headermiddle">
                <div>
                    <img src="{% static 'img/logoWhite.svg' %}" alt="dic1 shop logo">
                    <h1>Boutique de DIC1</h1>
                </div>
                
                {% block searchInput %}
                    <form role="search">
                        <input type="search" placeholder="Recherchez un produit..." aria-label="Search">
                        <button type="button">
                            <img src="{% static 'img/searchIcon.svg' %}" alt="search icon">
                        </button>
                    </form>
                {% endblock searchInput %}
                    
                <div>
                    <a href="{% url 'panier' %}"><img src="{% static 'img/cart-shop.svg' %}" alt="icon of cart-shopping"></a>
                    {% if request.user.is_authenticated %}
                        <div id = "profileDiv">
                            <img data-user-profileIcon src="{% static 'img/profile.svg' %}" alt="logo profile">
                            <div class = "hideUserNavCard userNavigationCard">
                                
                                {% if request.user.username %}
                                    <h2>Bienvenue {{ request.user.username }}</h2>
                                {% else %}
                                    <h2>Bienvenue...</h2>
                                {% endif %}
                                    
                                <div class = "wrapper">
                                    <a href="{% url 'params' %}" class = "customButton customButtonOne">Paramètre</a>
                                </div>
                                <div class = "wrapper wrapperV2">
                                    <a href="{% url 'profile' %}" class = "customButton customButtonOne">Profile</a>
                                </div>
                                <div class = "wrapper wrapperV2">
                                    <a href="{% url 'logout' %}" class = "customButton customButtonOne">Se déconnecter !</a>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <div id = "profileDiv">
                            <img data-user-profileIcon src="{% static 'img/profile.svg' %}" alt="logo profile">
                            <div class = "hideUserNavCard userNavigationCard">
                                <h2>Connexion ou Inscription</h2>
                                <div class = "wrapper">
                                    <a href="{% url 'user-signInRegister' %}" class = "customButton customButtonOne">Hey click moi !</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% block nav %}
                <nav id="headerbottom">
                    <img src="{% static 'img/home.svg' %}" alt="logo home">
                    <a href = "{% url 'home' %}">Accueil.</a>
                </nav>
            {% endblock nav %}
        </header>

        <main>
            {% block content %}
               Main content 
            {% endblock content %}    
        </main>

        <footer>
            <div id = "footerTop">
                <div>
                    <div>
                        <img src="{% static 'img/logoOrange.svg' %}" alt="dic1 shop logo">
                        <h1>Boutique de DIC1</h1>
                    </div>
                    <ul>
                        <li>Assistance client: <br> <span>775858575</span></li>
                        <li>4517 Aloup Kagne. <br> Sénégal,Thies EPT</li>
                        <li>ept@ept.sn</li>
                    </ul> 
                </div>
                    
                <div>
                    <h3>Catégorie supérieure</h3>
                    <ul>
                        <li><a href="#">Ordinateur et ordinateur portable</a></li>
                        <li><a href="#">Téléphone intelligent</a></li>
                        <li><a href="#">casque de musique</a></li>
                        <li><img src="{% static 'img/yellowDash.svg' %}" alt="yellow dash icon"><h4>Accessoires</h4></li>
                        <li><a href="#">Appareil photo et photo</a></li>
                        <li><a href="#">Télévision et maisons</a></li>
                        <li><a href="#">Parcourir tous les produits <img src="{% static 'img/yellowArrow.svg' %}" alt="right directed arrow logo"></a></li>
                    </ul>
                </div>

                <div>
                    <h3>Liens rapides</h3>
                    <ul>
                        <li><a href="#">Acheter le produit</a></li>
                        <li><a href="#">Panier</a></li>
                        <li><a href="#">Liste de souhaits</a></li>
                        <li><a href="#">comparateur</a></li>
                        <li><a href="#">Suivi de commande</a></li>
                        <li><a href="#">Aide client</a></li>
                        <li><a href="#">À propos de nous</a></li>
                    </ul>
                </div>

                <div>
                    <h3>Télécharger <br> l'application</h3>
                    <div>
                        <a href="#"><img src="{% static 'img/googleStore.svg' %}" alt="logo google play store"></a>
                        <p>
                            Obtenez le maintenant <br> <span>par Google</span>
                        </p>
                    </div>
                    <div>
                        <a href="#"><img src="{% static 'img/apple.svg' %}" alt="logo apple"></a>
                        <p>
                            Obtenez le maintenant <br> <span>Magasin d'applications</span>
                        </p>
                    </div>
                </div>

                <div>
                    <h3>Balise populaire</h3>
                    <div>
                        <em>Jeu</em>
                        <em>iPhone</em>
                        <em>la télé</em>
                        <em>Ordinateurs portables Asus</em>
                        <em>MacBook</em>
                        <em>SSD</em>
                        <em>Carte graphique</em>
                        <em>Banque de puissance</em>
                        <em>Smart TV</em>
                        <em>Conférencier</em>
                        <em>Tablette</em>
                        <em>Four micro onde</em>
                        <em>Samsung</em>
                    </div>
                </div>
            </div>
            <div></div>
        </footer>
        <script src="{% static 'js/script.js' %}"></script>
        {% block script %}{% endblock script %}
    </body>
</html>

templates/panier.html
{% extends 'base.html' %}
{% load static %}
{% load stars %}

{% block searchInput %}
                    
{% endblock searchInput %}

{% block nav %}
    <nav id="headerbottom">
        <img src="{% static 'img/home.svg' %}" alt="logo home">
        <a href = "{% url 'home' %}">Accueil.</a><span style="color: grey;">></span>
        <a href="#" style="color: rgb(70, 91, 226);">panier</a>
    </nav>
{% endblock nav %}



{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/stylepn.css' %}">
{% endblock style %}

{% block content %}
<div id = "userMessage"></div>
<div class="conteneur">
    <div class="panier">
        <h2>Panier</h2>
        <div id = "panier_grid">
            <h5>PRODUITS</h5>
            <h5>PRIX</h5>
            <h5>QUANTITE</h5>
            <h5>TOTAL</h5>
            
            {% for product in products %}
                <div class="produit {{ product.product_information.ASIN }}">
                    <img class="croix" src="{% static 'img/icons8-cancel-32.png' %}" alt="cancel">
                    <img class="imgarticle" src="{{ product.images.0 }}" alt="tv intelligent">
                    <p class="descpt">{{ product.title|slice:"0:50" }}...</p>
                </div>
                <span class="prix">{{product.list_price.0}} <span>$</span></span>
                <div class="compteur"><img class = "moins" src="{% static 'img/icons8-subtract-24.png' %}" alt="moins"> <span>{{ product.pan_quantity }}</span> <img class = "plus" src="{% static 'img/icons8-plus-24.png' %}" alt="plus"></div>
                <span class="total">{{product.list_price.0|fois:product.pan_quantity}} <span>$</span></span>
            {% endfor %}
                
        </div>
        
       <div class="one">
            <button id = "home_btn" type = "button"><img src="{% static 'img/icons8-left-24.png' %}" alt="fleche gauche"><a href="{% url 'home' %}">ACCEUIL</a></button>
            <button type = "button">VALIDER <a href="{% url 'valider' %}"></a></button>
        </div>
    </div>

    <div class="totaux">
        <h2>Totaux</h2>
        <div class="tot">
            <span>total</span>
            <span id = "total">320 <span>$</span></span>
        </div>
        <div class="tot">
            <span>frais</span>
            <span id="frais">16 <span>$</span></span>
        </div>
        <div class="tot">
            <span>taxe</span>
            <span id ="taxe">21.99 <span>$</span></span>
        </div>
        <hr>
        <div class="total1">
            <span>Total</span>
            <span id = "priceWithAllcharge">357.99 <span>$</span></span>
        </div>
    </div>
</div>
{% endblock content %}

{% comment %} Additionnal script {% endcomment %}

{% block script %}
    <script src="{% static 'js/panier.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock script %}

templates/parametre.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Parametre{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/para.css' %}">
{% endblock style %}

{% block searchInput %}
{% endblock searchInput %}

{% block nav %}
    <nav id="headerbottom">
        <img src="{% static 'img/home.svg' %}" alt="logo home">
        <a href = "{% url 'home' %}">Accueil.</a><span style="color: grey;">></span>
        <a href="#" style="color: rgb(70, 91, 226);">Compte de parametre</a>
    </nav>
{% endblock nav %}

{% block content %}
<div class="conteneur">
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert" >
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
    <div class="setting">
        <h2 class="para">PARAMÈTRE DU COMPTE</h2>
        <form class="form-para" method="post" action="" enctype = "multipart/form-data">
            {% csrf_token %}
            <div class="cercle">
                {% if request.user.profileImage %}
                    <img src="{{ MEDIA_URL }}{{ request.user.profileImage.url }}" alt="photo profile de l'utilisateur">
                {% endif %}
                <label for="id_profileImage">UserImage</label>
                <input type="file" name="profileImage" accept="image/*" id="id_profileImage">
            </div>
            <div class="form1">
                <div class="nom-email">
                    <div>
                        <label for="nom">Nom utilisateur</label><br>
                        <input name = "username" type="text" id="nom" placeholder="{{ request.user.username|default_if_none:'champ vide !!!' }}">
                    </div>
                    <div>
                        <label for="email">E-mail</label><br>
                        <input name = "email" type="email" id="email" placeholder=" {{ request.user.email }}">
                    </div>
                </div>
                <div class="email-num">
                    <div>
                        <label for="email sec">Email secondaire</label><br>
                        <input name = "secondEmail" type="email" id="email_sec" placeholder=" {{ request.user.secondEmail|default_if_none:'champ vide !!!' }}">
                    </div>
                    <div>
                        <label for="num">Numéro de téléphone</label><br>
                        <input name = "num" type="number" id="num" placeholder=" {{ request.user.tel|default_if_none:'champ vide !!!' }}">
                    </div>
                </div>
                <div class="adresse">
                    <label for="add">Adresse</label><br>
                    <input name = "address" type="text" id="add" placeholder=" {{ request.user.address|default_if_none:'champ vide !!!' }}">
                </div>
                <div class="location">
                    <div class="pays">
                        <label for="pays">Pays</label><br>
                        <select id="pays" name="pays">
                            <option disabled selected value> -- Choisis un pays -- </option>
                            <optgroup label="Afrique">
                                <option value="algerie">Sénégal</option>
                                <option value="tunisie">Tunisie</option>
                                <option value="maroc">Maroc</option>
                                <option value="madagascar">Madagascar</option>
                                <option value="benin">Bénin</option>
                                <option value="togo">Togo</option>
                            </optgroup>
                            <optgroup label="Europe">
                                <option value="france">France</option>
                                <option value="belgique">Belgique</option>
                                <option value="suisse">Suisse</option>
                            </optgroup>
                            <optgroup label="Amerique">
                                <option value="canada">Canada</option>
                            </optgroup>
                        </select>
                    </div>
                    <div class="region">
                        <label for="region">Région</label><br>
                        <select name="region" id="region">
                            <option disabled selected value> -- Choisis une region -- </option>
                            <option value="dakar">Dakar</option>
                            <option value="thies">Thiès</option>
                            <option value="saint-louis">Saint-Louis</option>
                        </select>
                    </div>
                    <div class="cp">
                        <label for="cp">Code Postal</label><br>
                        <input name = "zipCode" type="number" id="cp" placeholder="{{ request.user.zipCode|default_if_none:'champ vide !!!'}}">
                    </div>
                </div>   
                <button type="submit">SAUVEGARDER LES MODIFICATIONS</button>
            </div>
        </form>
    </div>
    <div class="mdp">
        <h2 class="changer">CHANGER LE MOT DE PASSE</h2>
        <form class="form2" method="post" action="{% url 'changePassword' %}">
                {% csrf_token %}
                <div>
                    <label for="mdp-actuel">Mot de passe actuel</label>
                    <div class = "passwordInput">
                        <input required maxLength = "30" type="password" name = "mdp-actuel"  id="mdp-actuel">
                        <img src="{% static 'img/eye-regular.svg' %}" alt="eye slash icon">
                    </div>
                </div>
                <div>
                    <label for="mdp-new">Nouveau mot de passe</label>
                    <div  class = "passwordInput">
                        <input required maxLength = "30" type="password" name = "mdp-new" id="mdp-new">
                        <img src="{% static 'img/eye-regular.svg' %}" alt="eye slash icon">
                    </div>
                </div>
                <div>
                    <label for="mdp-actuel">Confirmer le mot de passe</label>
                    <div class = "passwordInput">
                        <input required maxLength = "30" name = "mdp-new-confirm" type="password" id="mdp-new-confirm">
                        <img src="{% static 'img/eye-regular.svg' %}" alt="eye slash icon">
                    </div>
                </div>
                <button type="submit">CHANGER LE MOT DE PASSE</button>
        </form>
    </div>
</div>

{% endblock content %}

{% block script %}
    <script>
        let passwordEyeIcons = document.querySelectorAll(".passwordInput img");
        let passwordInputs = document.querySelectorAll(".passwordInput input");

        passwordEyeIcons.forEach((elt,idx) => {
            elt.addEventListener("click", e =>{
                if (passwordInputs[idx].getAttribute("type") == "password"){
                    elt.setAttribute("src","/static/img/eye-slash-regular.svg");
                    passwordInputs[idx].setAttribute("type","text");
                }else{
                    elt.setAttribute("src","/static/img/eye-regular.svg");
                    passwordInputs[idx].setAttribute("type","password");
                }
            });
        });
    </script>
{% endblock script %}

templates/produit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/produit.css' %}">
{% endblock style %}

{% comment %} {% block nav %}
<nav id="headerbottom">
    <img src="{% static 'img/home.svg' %}" alt="logo home">
    <a href = "#">Accueil.</a><span style="color: black;">></span>
    <a href="#">profil utilisateur</a>
</nav>
{% endblock nav %} {% endcomment %}

{% block searchInput %}{% endblock searchInput %}

{% block nav %}
    <nav id="headerbottom">
        <img src="{% static 'img/home.svg' %}" alt="logo home">
        <a href = "{% url 'home' %}">Accueil.</a><span style="color: grey;">></span>
        <a href="#" style="color: rgb(70, 91, 226);">produit</a>
    </nav>
{% endblock nav %}

{% block content %}
<div id = "userMessage"></div>
<div class="one">
    <span id="productAsin" style = "display:none;">{{ product.product_information.ASIN }}</span>
    <div class="image-produit">
        <img src="{{ product.images.0}}" alt="image produit">
    </div>
    <div class="panier-produit">
        <div>
            <div class="produit">{{ product.title }}
            </div>
            <div class="marque-categ">
                <p>Marque : <span>
                    {% if not product.product_information.Manufacturer %}
                        Absent
                    {% else %}
                        {{ product.product_information.Manufacturer }}
                    {% endif %}
                </span></p>
                <p>Catégorie : <span>
                    
                    {% for id_cat, cat in categories.items %}
                        {% if id_cat == product.product_category %}
                            {% if not product.product_information.Manufacturer %}
                                Absent
                            {% else %}
                                {{  cat }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                        
                </span></p>
            </div>
        </div>
        <div class="prix">
            {{ product.list_price.0 }} $
        </div>
        <div class="trait"></div>
       <div class="ajout-panier">
        <div class="compteur"><img class = "moins" src="{% static 'img/icons8-subtract-24.png' %}" alt="moins"> <span id = "quantity">01</span> <img class = "plus" src="{% static 'img/icons8-plus-24.png' %}" alt="plus"></div>
            <button>
                <span>AJOUTER A LA CARTE</span><span><img src="{% static 'img/cart-shop.svg' %}" alt="image chariot"></span>
            </button>
        </div>
        <div class="partager">
            <span>Partager le produit : </span><span><img src="{% static 'img/copy.svg' %}" alt="copy icon"></span>
            <span><img src="{% static 'img/icons8-facebook-30.png' %}" alt="facebook orange"></span>
            <span><img src="{% static 'img/twittergray.svg' %}" alt="twitter icon"></span>
            <span><img src="{% static 'img/pinterestgray.svg' %}" alt="pinterest icon"></span>
        </div>
        <div class="paiement">
            <p>Garantie à 100 % Paiement sécurisé</p>
            <p class="img-paiement">
                <span><img src="{% static 'img/paiement.svg' %}" alt="visa"></span>
            </p>
        </div>
    </div>
</div>
<div class="two">
    <div class="description">
        <div class="titre1">Description</div>
        <div class="descpt">{{ product.description.0 }}</div>
    </div>
    <div class="fonctionnalite">
        <div class="titre2">Fonctionnalité</div>
        <div class="fonct">
            <p><span><img src="{% static 'img/trophy.svg' %}" alt="icon medaille"></span><span></span>Garantie gratuite d'un an</p>
            <p><span><img src="{% static 'img/icons8-truck-50.png' %}" alt="livraison"></span><span>Livraison gratuite et livraison rapide</span></p>
            <p><span><img src="{% static 'img/handshake.svg' %}" alt="handshake icon"></span><span>Garantie de remboursement à 100 %</span></p>
            <p><span><img src="{% static 'img/headphone.svg' %}" alt="icon ecouteur"></span><span>Assistance client 24h/24 et 7j/7</span></p>
            <p><span><img src="{% static 'img/visa.svg' %}" alt="carte bancaire icon"></span><span>Mode de paiement sécurisé</span></p>
        </div>
    </div>
    <div class="information">
        <div class="titre3">Informations sur la livraison</div>
        <div class="info">
            <p><span>Courrier: </span>2 à 4 jours, livraison gratuite</p>
            <p><span>Expédition locale: </span>jusqu'à une semaine, 19 $.00</p>
            <p><span>Expédition terrestre UPS: </span>4 à 6 jours, 29 $.00</p>
            <p><span>Exportation mondiale Unishop: </span>3 à 4 jours, 39 $.00</p>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/produitScript.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock script %}

templates/profilutil.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Profile utilisateur{% endblock title %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profil.css' %}">
{% endblock style %}

{% block nav %}
<nav id="headerbottom">
    <img src="{% static 'img/home.svg' %}" alt="logo home">
    <a href = "{% url 'home' %}">Accueil.</a><span style="color: grey;">></span>
    <a href="#" style="color: rgb(70, 91, 226)">profil utilisateur</a>
</nav>
{% endblock nav %}


{% block searchInput %}
{% endblock searchInput %}

{% block content %}
<div class="conteneur">
    <div class="info">
        <div class="info1">INFOCOMPTE</div>
        <div class="info2">
            <div class="info3">
                <div class="cercle">
                    {% if request.user.profileImage %}
                        <img src="{{ MEDIA_URL }}{{ request.user.profileImage.url }}" alt="photo profile de l'utilisateur">
                    {% endif %}
                </div>
                <div>
                    <p class="nom">{{ request.user.username|default_if_none:"Unknow username..."}}</p>
                    <p class="add">{{ request.user.country|default_if_none:"Unknow country"}},{{ request.user.region|default_if_none:"Unknow city" }}</p>
                </div>
            </div>
            <p class="info4"><span>E-mail: </span> <span>{{ request.user.email }}</span></p>
            <p class="info4"><span>numéro de téléphone: </span> <span>{{ request.user.tel|default_if_none:"Tel non defini" }}</span></p>
            <p class="info4"><span>addresse: </span> <br> <span>{{ request.user.address|default_if_none:"Address non defini" }}</span></p>
        </div>
        <button class="modifier"><a href="{% url 'params' %}"></a>MODIFIER LE COMPTE</button>
    </div>

    <div class="commandes">
        <div class="commandea">
            <img src="{% static 'img/fusee1.svg' %}" alt="image commande">
            <div class="commande1">
                <p class="nbre">154</p>
                <p class="descpt">commandes totales</p>
            </div>
        </div>
        <div class="commandeb">
            <img src="{% static 'img/papier.svg' %}" alt="image commande">
            <div class="commande1">
                <p class="nbre">05</p>
                <p class="descpt">commandes en attente</p>
            </div>
        </div>
        <div class="commandec">
            <img src="{% static 'img/box1.svg' %}" alt="image commande">
            <div class="commande1">
                <p class="nbre">149</p>
                <p class="descpt">commandes terminées</p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}